DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS directory;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS tag;
DROP TABLE IF EXISTS comment;
DROP TABLE IF EXISTS tag_in_post;
DROP TABLE IF EXISTS manage_comment;
